workflow:
   name: 'Code Quality'
stages:
  - quality

# SonarQube Scan
sonarqube:
  stage: quality
  only:
    - main
    - merge_requests
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

# Qodana Scan
qodana:
  stage: quality
  only:
    - main
    - merge_requests
  variables:
    QODANA_TOKEN: $qodana_token
  image:
    name: jetbrains/qodana-python
    entrypoint: [""]
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana