workflow:
   name: 'Code Quality'

stages:
  - quality

sonarqube:
  stage: quality
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - main

qodana:
  stage: quality
  image:
    name: jetbrains/qodana-<linter>
    entrypoint: [ "" ]
  cache:
    - key: qodana-2024.1-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2024.1-$CI_DEFAULT_BRANCH-
        - qodana-2024.1-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - qodana --cache-dir=$CI_PROJECT_DIR/.qodana/cache
  only:
    - main
    - merge_requests